# Generated by Django 2.2.7 on 2019-11-30 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('holesDetected', models.IntegerField(blank=True, null=True)),
                ('totalAvgAcc', models.FloatField(blank=True, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buraco.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Buraco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=20)),
                ('acc', models.FloatField()),
                ('user', models.ManyToManyField(blank=True, null=True, to='buraco.Cidadao')),
            ],
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastKnownLat', models.DecimalField(decimal_places=7, max_digits=20)),
                ('lastKnownLon', models.DecimalField(decimal_places=7, max_digits=20)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buraco.Usuario')),
            ],
        ),
    ]
