# Generated by Django 2.2.7 on 2019-11-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buraco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastKnownLat', models.CharField(max_length=20)),
                ('lastKnownLon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('holesDetected', models.IntegerField(max_length=20)),
                ('totalAvgAcc', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='buraco',
            name='user',
            field=models.ManyToManyField(to='buraco.User'),
        ),
    ]
